server:
  port: 8085
  servlet:
    context-path: /

spring:
  application:
    name: iam-admin-service

  # ===== OAuth2 Client (授权码登录认证中心) =====
  security:
    oauth2:
      client:
        registration:
          admin-app:
            provider: iam
            client-id: admin-app
            client-secret: 123456
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8085/login/oauth2/code/admin-app
            scope: openid,profile,read,write
            client-name: 管理后台
        provider:
          iam:
            issuer-uri: http://localhost:9000

# ===== 管理后台服务自定义配置 =====
iam:
  admin-web-url: http://localhost:8001
  auth-center-base-url: http://localhost:9000
  resource-service-base-url: http://localhost:9010

logging:
  level:
    root: INFO
    net.xzh.admin: DEBUG
    org.springframework.security.oauth2: DEBUG
